liip:
    resource: '@PiedWebCMSBundle/Resources/config/routes/liip_imagine.yaml'

user:
    resource: '@PiedWebCMSBundle/Resources/config/routes/user.yaml'

admin:
    resource: '@PiedWebCMSBundle/Resources/config/routes/admin.yaml'

piedweb_cms_homepage:
    path:     /
    controller: PiedWeb\CMSBundle\Controller\PageController::show
    methods:    [GET, HEAD]

media:
    resource: '@PiedWebCMSBundle/Resources/config/routes/media.yaml'

page:
    resource: '@PiedWebCMSBundle/Resources/config/routes/page.yaml'
