liip_imagine:
    cache: piedweb_relativeimgcache

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%'
    #resolvers:
       #default:
          #web_path:
            #cache_prefix: "media"
    #resolvers:
        #default:
            #flysystem:
                #filesystem_service: oneup_flysystem.media_filesystem
                #root_url:           "https://http://127.0.0.1:8000/media/"
                #cache_prefix:       public/media
                #visibility:         public

    filter_sets:
        small_thumb:
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                thumbnail: { size : [150, 150], mode : outbound }
            #post_processors:
             #   jpegoptim: { strip_all: true, max: 70, progressive: true }
              #  mozjpeg: { quality: 70 }
        thumb:
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                thumbnail: { size : [306, 306], mode : outbound }

        height_300:
            quality: 90
            jpeg_quality:          90
            png_compression_level: 9
            filters:
                relative_resize:
                    heighten: 300


        xs: #576px
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 576
                auto_rotate: ~
                strip: ~
        sm: #768px
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 768
                auto_rotate: ~
                strip: ~
        md: #992px
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 992
                auto_rotate: ~
                strip: ~
        lg: #1200px
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 1200
                auto_rotate: ~
                strip: ~
        xl: #1200px+
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                relative_resize:
                    widen: 1400
                auto_rotate: ~
                strip: ~

        default:
            quality: 80
            jpeg_quality:          80
            png_compression_level: 8
            filters:
                downscale:
                    max: [1980, 1280]
                auto_rotate: ~
                strip: ~



